answers = ds_map_create();
ds_map_add(answers, inst_30A2E1E, "boolean color;")
ds_map_add(answers, inst_54D9CE89, "void")
ds_map_add(answers, inst_7C37CCE1, "setColor")
ds_map_add(answers, inst_3F100F75, "boolean inColor")
ds_map_add(answers, inst_752E3BFF, "color")
ds_map_add(answers, inst_3C233ADB, "inColor")
ds_map_add(answers, inst_4DA46840, "Loady")
ds_map_add(answers, inst_85FEF67, "setColor")
ds_map_add(answers, inst_5693B04B, "True")