answers = ds_map_create();
ds_map_add(answers, inst_3D88D098, "String concat1")
ds_map_add(answers, inst_5A56AD17, "intro + name;")
ds_map_add(answers, inst_6A845AB0, "concat1")
ds_map_add(answers, inst_9C06DFC, "char space")
ds_map_add(answers, inst_4F7706B8, "' '")
ds_map_add(answers, inst_2E25FF24, "intro + space + name;")
ds_map_add(answers, inst_BBD7F1A, "full2")
ds_map_add(answers, inst_401A3241, "beg + num + end;")
ds_map_add(answers, inst_2AFD6398, "sentence")